#! /bin/bash

# bspwm
mkdir -p $HOME/.config/bspwm
ln -s $PWD/bspwmrc $HOME/.config/bspwm/bspwmrc 2>/dev/null \
	&& chmod +x $HOME/.config/bspwm/bspwmrc \
	&& echo "Installing bspwm config" \
	|| echo "Bspwm is already configured"

# sxhkd
mkdir -p $HOME/.config/sxhkd
ln -s $PWD/sxhkdrc $HOME/.config/sxhkd/sxhkdrc 2>/dev/null \
	&& chmod +x $HOME/.config/sxhkd/sxhkdrc \
	&& echo "Installing sxhkd config" \
	|| echo "Sxhkd is already configured"

# i3
mkdir -p $HOME/.config/i3
ln -s $PWD/i3config $HOME/.config/i3/config 2>/dev/null \
	&& chmod +x $HOME/.config/i3/config \
	&& echo "Installing i3 config" \
	|| echo "I3 is already configured"
